### ISSUE TITLE
Coverage gone down with new release

### ISSUE THREAD

**Issue by karanveerm** [IainNZ/Coverage.jl#40]
Hi,

With the new Coverage release, the coverage for Convex.jl seems to have gone down from 92% to 57%

Looking at https://coveralls.io/builds/1700000 and comparing it to https://coveralls.io/builds/1707677 (both are the same commit on different branches- the former was using the previous version of Coverage), it seems like the number of files covered also went down from 31 to 8.

Would this be a Coverage.jl bug? Thanks!

**Comment by timholy** [comment]
For the number of files, that looks like a bug: I seem to have broken the recursive descent into subfolders. Thanks for reporting it; I'll fix this pronto.

For the change in the coverage %age, see https://groups.google.com/d/msg/julia-users/h7rtp5RC9Eo/dJYfotrsXGYJ. The bottom line is our old method of calculating coverage %age was completely bogus; you could have had a file with 1000 1-line function, test a single one of them, and get scored as having 100% test coverage. If you browse through the old coverage reports, you'll see a lot of lines that were never executed labeled in green. They should be red in the new reports.

**Comment by timholy** [comment]
OK fixed, and a new release tag. Next time you push a commit to Travis, it will use the corrected one.
