### ISSUE TITLE
.cov file in coveralls

### ISSUE THREAD

**Issue by karanveerm** [IainNZ/Coverage.jl#43]
https://coveralls.io/builds/1752035 has a file called `src/dcp.jl.cov` (no other file has a .cov) and I can't seem to figure out why that would be the case specifically with just the [dcp.jl](https://github.com/JuliaOpt/Convex.jl/blob/master/src/dcp.jl) file. Would this be a bug, or am I doing something wrong?

**Comment by timholy** [comment]
That file shouldn't even be in there, it's the rest that are the ones you want. What does the output of Coverage look like when you [run it locally](https://github.com/IainNZ/Coverage.jl)?

**Comment by IainNZ** [comment]
I can't see it in that Coveralls link, but can you send the Travis log for that build?

**Comment by karanveerm** [comment]
@IainNZ: https://coveralls.io/jobs/4042288 and https://travis-ci.org/JuliaOpt/Convex.jl/jobs/47195102#L2435
If you look at line 2435, it doesn't say "Skipped src/dcp.jl.cov" as it did for other .cov files

@timholy: Are you asking for the output of dcp.jl.cov? It looks like this: https://gist.github.com/karanveerm/efe5c3e7589a5611eb63

The output of `using Coverage; covered, tot = coverage_folder()
` looks like this: https://gist.github.com/karanveerm/489a63c97e8f017a7511

These are all for the same commit. I'm on Julia 0.3.3 locally.

**Comment by IainNZ** [comment]
Wooah, weird.

**Comment by karanveerm** [comment]
It seems like `.cov`  files are expected to error out in this function: https://github.com/IainNZ/Coverage.jl/blob/master/src/Coverage.jl#L35 and only when the error is caught, the file is skipped
```
    open(filename) do io
           while !eof(io)
               #pos = position(io)
               ast = Parser.parse(io)
           end
       end
```
This errors out for all `.cov` files except `dcp.jl.cov`.

I guess the simplest fix would be to skip any file with a `.cov`extension over here: https://github.com/IainNZ/Coverage.jl/blob/master/src/Coverage.jl#L140, although I haven't looked at the code closely enough to make an informed PR.

**Comment by IainNZ** [comment]
I'm going to close this for now, quite a few things have changed so its possibly its resolved.
