### ISSUE TITLE
Don't submit files that have a coverage file generated, but its all NULL?

### ISSUE THREAD

**Issue by IainNZ** [IainNZ/Coverage.jl#45]
e.g. https://coveralls.io/jobs/4081886 's `SimJulia.jl`

So the file is exectued, so a coverage file is generated, but there are no coverable lines, so its going to weigh down the coverage (maybe? not sure how the overall figure is generated)

**Comment by garborg** [comment]
It hasn't seemed like it weighs down coverage when I've looked. In this case, for example, it doesn't:
https://coveralls.io/builds/1767792
julia> (0+35+23+49)/(0+38+24+50)
0.9553571428571429

I'd be for leaving the files in, so source files aren't missing, so there's less left to trust in the toolchain for the curious user.

**Comment by IainNZ** [comment]
Ah in that case, thats fine
