### ISSUE TITLE
@parallel code coverage

### ISSUE THREAD

**Issue by wildart** [IainNZ/Coverage.jl#52]
I found that code wrapped with ``@parallel`` macro is not covered. Is that an issue with all macros?

**Comment by timholy** [comment]
No, but it is an issue with anything that uses multiple processes. Currently we don't have a mechanism to have each worker report its own coverage and send them back to the main process for consolidation.

Pull requests are welcome, of course. (This would need to be implemented in julia proper, not Coverage.jl.)

**Comment by wildart** [comment]
Got it. Thank for an explanation.
