### ISSUE TITLE
Coverage doesn't work on 0.4?

### ISSUE THREAD

**Issue by tlycken** [IainNZ/Coverage.jl#54]
There seems to be a problem with submitting coverage results on 0.4 for at least https://github.com/JuliaLang/ODE.jl - I can't tell if it's because we have an outdated format in our `.travis.yml` or because something is actually broken, but all our tests pass, and then the build script fails when collecting and submitting coverage results.

You can check out a couple of build logs [here](https://travis-ci.org/JuliaLang/ODE.jl/builds/55938753) and [here](https://travis-ci.org/JuliaLang/ODE.jl/builds/55936609) (there are a few more in the build history of that project).

This is probably an error on our side, because http://pkg.julialang.org/pulse.html doesn't indicate a major breakage (which I would have expected if this was a problem in your end). However, it would still be nice with some assistance in seeing what's the cause :)

**Comment by IainNZ** [comment]
I don't know much about the latest on 0.4, I don't really use it, but

```
ERROR: LoadError: LoadError: LoadError: error in method definition: function Base.parse must be explicitly imported to be extended
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:54
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:51
 in process_options at ./client.jl:292
 in _start at ./client.jl:402
while loading /home/travis/.julia/v0.4/JuliaParser/src/parser.jl, in expression starting on line 1864
while loading /home/travis/.julia/v0.4/JuliaParser/src/JuliaParser.jl, in expression starting on line 6
```

Looks like JuliaParser is somewhat broken? (@jakebolewski)

**Comment by IainNZ** [comment]
The pulse is out-of-date, but 0.4 was pretty broken when i was last able to run it, by the way

**Comment by tlycken** [comment]
Is there anything I can do with the `.travis.yml` file to make these builds pass, except not upload coverage stats? (In other words, is there a workaround?) I don't understand enough about the problem to be able to fix it myself...

**Comment by IainNZ** [comment]
The coveralls bit should be in an `after_success` block, not part of the test. Look at e.g. Distributions.jl. That should be enough I think

**Comment by IainNZ** [comment]
Looks like the underlying issue is fixed: https://github.com/jakebolewski/JuliaParser.jl/issues/18

**Comment by tlycken** [comment]
Yup; the bulids in the referencing PR above completed successfully, so I think this is fixed now. Thanks (both to you and to @jakebolewski)!
