### ISSUE TITLE
Codecov.io support

### ISSUE THREAD

**Issue by IainNZ** [IainNZ/Coverage.jl#57]
API looks pretty similar to Coveralls, so should be easy enough.

**Comment by stevepeak** [comment]
Can you show me an example `json` coverage output that I can parse server side. Thanks!

**Comment by IainNZ** [comment]
We currently just export in the Coveralls.io JSON format. The raw coverage data is in the form of lines where the first 9 columns are a count and the rest is the actual line. This package reads that in, and currently mangles it into Codecov.io's JSON format if its different. It looks mostly the same

**Comment by IainNZ** [comment]
https://twitter.com/iaindunning/status/595235822804275201

**Comment by kshyatt** [comment]
OK, I have this ALMOST working but I'm still getting HTTP 200 when I try to POST the results to codecov with the repo token included.

**Comment by IainNZ** [comment]
Http200 means success - is there a message?

**Comment by kshyatt** [comment]
Yeah! I got it to work! I was stupid and didn't refresh the repo... anyway we now have BASE COVERAGE ON CODECOV :tada: :fireworks: I'll submit PRs to you and to `CoverageBase` with my changes!

**Comment by IainNZ** [comment]
Wow neat.
@stevepeak we should be getting a released version soon, and a lot of Julia packages will instantly be able to start using CodeCov.io. BTW, your badge format isn't really the same as the other ones, might need to generate new ones using shield.io?

**Comment by kshyatt** [comment]
NB: Right now, `submit_token` expects that you are NOT running on CI, and scrapes the branch and commit info directly from git. I did that because that's how the Coveralls version works right now too. If people want it some other way I am happy to add more other CI services in!

**Comment by IainNZ** [comment]
If you've got any more Coverage.jl time, could you update the README with how to use Codecov instead of Coveralls?

**Comment by kshyatt** [comment]
Yes!

**Comment by julian-gehring** [comment]
There may still be a problem with codecov support. The current HTTP return code is 400, with the message `data: ASCIIString "template not found at html/errors/400.html"` (see the build reports of travis: https://travis-ci.org/IainNZ/Coverage.jl/jobs/69379891). Also the codecov summary page does not show new commits, the last one shown is two months old: https://codecov.io/github/IainNZ/Coverage.jl.
