### ISSUE TITLE
Crash with greek symbols

### ISSUE THREAD

**Issue by ovainola** [IainNZ/Coverage.jl#59]
Hello,

We're creating a new finite element solver for Julia and we're using Travis CI & Coverage.jl + Coveralls.io for testing. We had a problem when we uploaded our code to github and it started to build code via travis, tests went fine but it didn't upload coverage to Coveralls.io. After checking the log file from travis, it seems that Coverage.jl crashed in the Coveralls.process_folder() -function when it was processing greek symbols inside our functions. After replacing all the greek symbols with plain text, coverage started working fine. 

Here's a log file from travis:

    $ julia -e 'cd(Pkg.dir("JuliaFEM")); Pkg.add("Coverage"); using Coverage;  
    Coveralls.submit(Coveralls.process_folder())'
    INFO: Cloning cache of BinDeps from git://github.com/JuliaLang/BinDeps.jl.git
    INFO: Cloning cache of Codecs from git://github.com/dcjones/Codecs.jl.git 
    INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
    INFO: Cloning cache of Coverage from git://github.com/IainNZ/Coverage.jl.git
    INFO: Cloning cache of Dates from git://github.com/quinnj/Dates.jl.git
    INFO: Cloning cache of FactCheck from git://github.com/JuliaLang/FactCheck.jl.git
    INFO: Cloning cache of GnuTLS from git://github.com/JuliaWeb/GnuTLS.jl.git
    INFO: Cloning cache of HttpCommon from git://github.com/JuliaWeb/HttpCommon.jl.git
    INFO: Cloning cache of HttpParser from git://github.com/JuliaWeb/HttpParser.jl.git
    INFO: Cloning cache of JSON from git://github.com/JuliaLang/JSON.jl.git
    INFO: Cloning cache of JuliaParser from git://github.com/jakebolewski/JuliaParser.jl.git
    INFO: Cloning cache of Nettle from git://github.com/staticfloat/Nettle.jl.git
    INFO: Cloning cache of Requests from git://github.com/JuliaWeb/Requests.jl.git
    INFO: Cloning cache of SHA from git://github.com/staticfloat/SHA.jl.git
    INFO: Cloning cache of URIParser from git://github.com/JuliaWeb/URIParser.jl.git
    INFO: Installing BinDeps v0.3.12
    INFO: Installing Codecs v0.1.4
    INFO: Installing Compat v0.4.5
    INFO: Installing Coverage v0.0.8
    INFO: Installing Dates v0.3.2
    INFO: Installing FactCheck v0.2.7
    INFO: Installing GnuTLS v0.0.4
    INFO: Installing HttpCommon v0.0.12
    INFO: Installing HttpParser v0.0.11
    INFO: Installing JSON v0.4.3
    INFO: Installing JuliaParser v0.6.2
    INFO: Installing Nettle v0.1.8
    INFO: Installing Requests v0.0.8
    INFO: Installing SHA v0.0.4
    INFO: Installing URIParser v0.0.5
    INFO: Building HttpParser
    INFO: Changing Directory to /home/travis/.julia/v0.3/HttpParser
    Submodule 'deps/src/http-parser' (https://github.com/joyent/http-parser.git) registered for path   
    'deps/src/http-parser'
    Cloning into 'deps/src/http-parser'...
    remote: Counting objects: 1354, done.
    remote: Total 1354 (delta 0), reused 0 (delta 0), pack-reused 1354
    Receiving objects: 100% (1354/1354), 687.14 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (804/804), done.
    Checking connectivity... done.
    INFO: Changing Directory to /home/travis/.julia/v0.3/HttpParser
    INFO: Changing Directory to /home/travis/.julia/v0.3/HttpParser/deps/src
    INFO: Attempting to Create directory /home/travis/.julia/v0.3/HttpParser/deps/usr/lib
    INFO: Changing Directory to /home/travis/.julia/v0.3/HttpParser/deps/src
    make: Entering directory `/home/travis/.julia/v0.3/HttpParser/deps/src/http-parser'
    cc -I. -DHTTP_PARSER_STRICT=0  -Wall -Wextra -Werror -O3  -fPIC -c http_parser.c -o    
    libhttp_parser.o
    cc -shared -o libhttp_parser.so libhttp_parser.o
    make: Leaving directory `/home/travis/.julia/v0.3/HttpParser/deps/src/http-parser'
    INFO: Changing Directory to /home/travis/.julia/v0.3/HttpParser/deps/src
    INFO: Building Nettle
    INFO: Building GnuTLS
    INFO: Package database updated
    WARNING: This version of the GnuTLS library (2.12.14) is deprecated
    and contains known security vulnerabilities. Please upgrade to a
    more recent version.
    []
    src/JuliaFEM.jl
    src/shape_functions.jl
    ASCIIString "{\"message\":\"Build processing error.\",\"error\":true,\"url\":\"\"}"

Here's an issue, which we already closed
https://github.com/ovainola/JuliaFEM/issues/3

**Comment by IainNZ** [comment]
Thats strange, because many packages use Greek symbols with Coverage.jl just fine. I'll investigate when I get a chance (will not be soon).

**Comment by TeroFrondelius** [comment]
I had the same issue with my FooBar package. I now corrected it, based on @ovainola .travis.yml, and these are the small changes in my .travis.yml: I removed --check-bounds=yes and added Pkg.init(). 
https://github.com/TeroFrondelius/FooBar.jl/commit/da91a903d45988b6e64ff44723c3c0e8ce09ab9d?diff=split

Can these have anything to do with this issue?

**Comment by IainNZ** [comment]
I don't know, I don't see why it would. That Travis file is messed up by the way, it runs the tests twice.

**Comment by TeroFrondelius** [comment]
Thanks. I removed the later unnecessary testing. Everything still works. This FooBar is a "empty" package for practicing the github settings.
