### ISSUE TITLE
Codecov not working properly?

### ISSUE THREAD

**Issue by IainNZ** [IainNZ/Coverage.jl#67]
https://travis-ci.org/IainNZ/Coverage.jl/jobs/69546905

```
Response 
  status: Int64 400
  headers: Dict{String,String} len 15
    Connection: ASCIIString "keep-alive"
    Via: ASCIIString "1.1 vegur"
    Date: ASCIIString "Sat, 04 Jul 2015 15:16:01 GMT"
    Access-Control-Allow-Origin: ASCIIString "*"
    http_minor: ASCIIString "1"
    Keep-Alive: ASCIIString "1"
    status_code: ASCIIString "400"
    X-Request-Id: ASCIIString "50894325-25a6-4525-a8c5-89e4bc774b17"
    Server: ASCIIString "Cowboy"
    Content-Length: ASCIIString "42"
    Vary: ASCIIString "Accept-Encoding"
    ...
  data: ASCIIString "template not found at html/errors/400.html"
  finished: Bool true
```

@stevepeak 

Looks like the error message is screwed so its hard to know what went wrong.

**Comment by julian-gehring** [comment]
Could be related to the changes in #57.

**Comment by IainNZ** [comment]
Well seeing as thats the PR where I implemented it, I think thats a safe assumption!

**Comment by IainNZ** [comment]
The thing is its working fine for @kshyatt for Base coverage and one of her packages, so I'm wondering if it something weird to do with branches on Codecovs end.

**Comment by kshyatt** [comment]
It was working for me last night, I'm a bit busy today if someone else wants to take a look.

**Comment by stevepeak** [comment]
Everything on Codecov end is going well.. I do see the logs of this ci build. However the logs do not show the reason why. I'll dig in more...

**Comment by kshyatt** [comment]
Codecov just worked perfectly well for me for `CUSPARSE.jl`. This was running on my local machine, not Travis.

**Comment by felipenoris** [comment]
I'm getting the same issue here: https://travis-ci.org/felipenoris/BusinessDays.jl.
Both Coveralls and Codecov are not working.
I guess that's something related to the "Cowboy" on the error message. lol

**Comment by kshyatt** [comment]
If Coveralls isn't working that suggests a problem on my end, not theirs.

**Comment by felipenoris** [comment]
@kshyatt I'm a "first-timer" user of Coverage. Never worked for me so far, so it could be a problem located between my keyboard and my chair. Btw, you do a marvelous job here.

**Comment by kshyatt** [comment]
I haven't tried it on Travis. Do you happen to have your Travis log that I might be able to take a look at?

**Comment by felipenoris** [comment]
The log is here: https://travis-ci.org/felipenoris/BusinessDays.jl . If you cannot open the link, let me know and I'll post here.

**Comment by kshyatt** [comment]
Ok, so it looks like the coverage is getting sent to Coveralls correctly from Travis, and you're having the same Codecov trouble as in the OP. But the coverage numbers themselves appear to be messed up, right?

**Comment by felipenoris** [comment]
Well, I'm getting 0% Coverage.

**Comment by kshyatt** [comment]
Yes, because the `.cov` files are either being generated or processed incorrectly. But the `Coveralls.submit()` is working correctly, so it's something I've done wrong :)

**Comment by felipenoris** [comment]
Please, don't be so hard on yourself. :+1:

**Comment by felipenoris** [comment]
After a few hours of debugging, I found out that all you need is to tag a new version and publish Coverage.jl to metadata. I added Pkg.checkout("Coverage"); to my travis script and it just worked.
https://travis-ci.org/felipenoris/BusinessDays.jl 
:+1:

**Comment by kshyatt** [comment]
@IainNZ could you tag a new version please

**Comment by IainNZ** [comment]
@kshyatt please just tag whenever you need to, I don't have good internet access this week.

**Comment by IainNZ** [comment]
I'm doing it now though

**Comment by tkelman** [comment]
@kshyatt mentioned she was hitting https://github.com/JuliaLang/julia/issues/10766 so unable to use `Pkg.publish`

**Comment by IainNZ** [comment]
Ah right. Maybe I should move this to JuliaCI?

**Comment by tkelman** [comment]
Not a bad idea. Who else has commit access here, I just invited Katie and Tim Holy to the JuliaCI org.

**Comment by IainNZ** [comment]
@staticfloat @kshyatt @timholy are the people with access to Coverage right now, so, same really. I have owner status with JuliaCI apparently so I could do it right now.

**Comment by felipenoris** [comment]
Ok, I guess I was not 100% correct on my statement.
By using Pkg.checkout("Coverage") , travis works for coveralls.io , but **not for Codecov**.
But, running the following script **locally** worked for Codecov.
```
#!/bin/bash
REPO_TOKEN=$YOUR_TOKEN_HERE julia -e 'cd(Pkg.dir("MyPkg")); using Coverage;  Codecov.submit_token(Codecov.process_folder())'
```
After some more digging, I found out that when it works, I get this last message :
```
HttpCommon.Response 
  status: Int64 200
  headers: Dict{AbstractString,AbstractString} len 15
    Connection: ASCIIString "keep-alive"
    Via: ASCIIString "1.1 vegur"
    Date: ASCIIString "Sun, 12 Jul 2015 20:15:06 GMT"
    Access-Control-Allow-Origin: ASCIIString "*"
    http_minor: ASCIIString "1"
    Keep-Alive: ASCIIString "1"
    status_code: ASCIIString "200"
    X-Request-Id: ASCIIString "4811b752-5ef4-4af1-8487-9352d7677bb1"
    Server: ASCIIString "Cowboy"
    Content-Length: ASCIIString "48"
    Vary: ASCIIString "Accept-Encoding"
    ...
  data: ASCIIString "template not found at html/upload_post_many.html"
  finished: Bool true
```

If I use a **wrong token** I get the same results as the original post by @IainNZ : 
```
HttpCommon.Response 
  status: Int64 400
  headers: Dict{AbstractString,AbstractString} len 15
    Connection: ASCIIString "keep-alive"
    Via: ASCIIString "1.1 vegur"
    Date: ASCIIString "Sun, 12 Jul 2015 20:24:49 GMT"
    Access-Control-Allow-Origin: ASCIIString "*"
    http_minor: ASCIIString "1"
    Keep-Alive: ASCIIString "1"
    status_code: ASCIIString "400"
    X-Request-Id: ASCIIString "3dfd822d-3b84-498d-b664-fae5bbe40240"
    Server: ASCIIString "Cowboy"
    Content-Length: ASCIIString "42"
    Vary: ASCIIString "Accept-Encoding"
    ...
  data: ASCIIString "template not found at html/errors/400.html"
  finished: Bool true
```

Which makes me think that Coverare.jl is fine, but Travis is getting the wrong Codecov REPO_TOKEN.

**Comment by staticfloat** [comment]
Could what is happening be that because `Coverage.jl` uses `REPO_TOKEN` for both `Coveralls` and `Codecov`, only one is getting the correct token?

**Comment by felipenoris** [comment]
@staticfloat I may be wrong, but I don't think so.
I just removed Coveralls submit from my travis script. I also tried to list my REPO_TOKEN (please don't do this at home without parents supervision). My travis script was:
```
after_success:
  - echo $REPO_TOKEN
  - julia -e 'cd(Pkg.dir("BusinessDays")); using Coverage; Codecov.submit(Codecov.process_folder())'
```

The echo part listed nothing, so maybe $REPO_TOKEN was not set.

**Comment by kshyatt** [comment]
Hey guys, I'm really sorry my terrible PRs caused this huge disaster. I wish I could figure out what's going on :(

**Comment by felipenoris** [comment]
Are you sure this worked before on travis, without passing the user token, with https://codecov.io/upload/v1?

**Comment by kshyatt** [comment]
I hadn't tried it on Travis, only locally.

**Comment by felipenoris** [comment]
It turns out that it may never worked before.
I changed to V2 URL and it's now working.
https://github.com/IainNZ/Coverage.jl/pull/71.

**Comment by felipenoris** [comment]
Should this issue be closed?

**Comment by IainNZ** [comment]
Fixed now
