### ISSUE TITLE
process_file() not working

### ISSUE THREAD

**Issue by kersulis** [IainNZ/Coverage.jl#75]
I'm trying to set up code coverage with my [MatpowerCases.jl][1] package. I can't get Coveralls to report code coverage; it says it cannot find coverage data. I suspect this problem is related to an error I get when I try to use Coverage locally.

The README instructions worked well for me until I ran `covered_lines, total_lines = coverage_folder()`. This was the output:
```julia
src/MatpowerCases.jl
Skipped src/MatpowerCases.jl
src/MatpowerCases.jl.cov
Skipped src/MatpowerCases.jl.cov
0-element Array{Any,1}
```
So Coverage skipped the only `.cov` file in `src/`. But when I use `covered_lines,total_lines = coverage_file("src/MatpowerCases.jl")`, I get this:
```julia
(11,13)
```
which matches visual inspection of the `MatpowerCases.jl.cov` file in `src/`.

I went digging in the code and found that my `.cov` file is being skipped because [this line][2] throws an error, so I ran it in a REPL and got this:
```julia
julia> new_sf = Coveralls.process_file("src/MatpowerCases.jl.cov","src")
ERROR: `convert` has no method matching convert(::Type{Int64}, ::Nothing)
 in setindex! at array.jl:307
 in merge_coverage_counts at /home/jkersulis/.julia/v0.3/Coverage/src/Coverage.jl:22
 in process_cov_with_pids at /home/jkersulis/.julia/v0.3/Coverage/src/Coverage.jl:83
 in process_file at /home/jkersulis/.julia/v0.3/Coverage/src/Coverage.jl:194
```
So it traces back to [this function][3]. Why is my package having this problem?

[1]: https://github.com/kersulis/MatpowerCases.jl
[2]: https://github.com/IainNZ/Coverage.jl/blob/master/src/Coverage.jl#L220
[3]: https://github.com/IainNZ/Coverage.jl/blob/master/src/Coverage.jl#L16

**Comment by IainNZ** [comment]
The wrong "skip" is actually the first one, the messages are silly. Can you try
```
Coveralls.process_file("src/MatpowerCases.jl","src")
```

**Comment by kersulis** [comment]
Whoops, sorry about that.

Looks like the error is the same:
```julia
julia> Coveralls.process_file("src/MatpowerCases.jl","src")
ERROR: `convert` has no method matching convert(::Type{Int64}, ::Nothing)
 in setindex! at array.jl:307
 in merge_coverage_counts at /home/jkersulis/.julia/v0.3/Coverage/src/Coverage.jl:22
 in process_cov_with_pids at /home/jkersulis/.julia/v0.3/Coverage/src/Coverage.jl:83
 in process_file at /home/jkersulis/.julia/v0.3/Coverage/src/Coverage.jl:194
```

**Comment by kersulis** [comment]
[Here](https://gist.github.com/kersulis/40c9c03ecdd9efa14831) is my coverage file.

Update: I found that
```julia
process_cov("src/MatpowerCases.jl.cov")
```
returns an array with one entry per line of code, but 
```julia
process_cov_with_pids("src/MatpowerCases.jl.cov","src")
```
or
```julia
process_cov_with_pids("src/MatpowerCases.jl","src")
```
both throw this error:
```julia
ERROR: `convert` has no method matching convert(::Type{Int64}, ::Nothing)
 in setindex! at array.jl:307
 in merge_coverage_counts at /home/jkersulis/.julia/v0.3/Coverage/src/Coverage.jl:22
 in process_cov_with_pids at /home/jkersulis/.julia/v0.3/Coverage/src/Coverage.jl:83
```

**Comment by kshyatt** [comment]
I think your problem is that you are using 0.3. The change to use PIDs was made only on 0.4. But I might have made an implicit assumption when I updated the code that requires 0.4. Let me take a look - Coverage.jl obviously still needs to work with 0.3!

**Comment by IainNZ** [comment]
Fixed now

**Comment by kersulis** [comment]
Everything works locally, and [Coveralls](https://coveralls.io/github/kersulis/MatpowerCases.jl) matches what I see on my machine. Thanks!
