### ISSUE TITLE
`module X` incorrectly marked as not covered?

### ISSUE THREAD

**Issue by IainNZ** [IainNZ/Coverage.jl#81]
Something different about how Base.parse works, perhaps

**Comment by IainNZ** [comment]
e.g. https://codecov.io/github/JuliaLang/JSON.jl/src/JSON.jl?ref=14eecd91bccabed3074d92759e17ed38c8cf0ac0

**Comment by IainNZ** [comment]
https://codecov.io/github/staticfloat/SHA.jl/src/SHA.jl?ref=98f4e9946bf7862adef630f34a27fcbf85e8170e
So its definitely not jus the first line, its just that it marks module as coverable, but it isn't

**Comment by IainNZ** [comment]
I imagine the fix is just special casing something, however, I really shouldn't look at this right now, staring at a deadline D:

**Comment by kshyatt** [comment]
I am also staring down a deadline.

**Comment by IainNZ** [comment]
I'll get to it by the weekend I think. It isn't hurting anyone :+1:
