### ISSUE TITLE
Coveralls submit broken

### ISSUE THREAD

**Issue by kshyatt** [IainNZ/Coverage.jl#86]
https://github.com/IainNZ/Coverage.jl/blob/master/src/coveralls.jl#L108

Looks like `Requests` no longer exports `post`.

**Comment by IainNZ** [comment]
@malmaud what do

**Comment by IainNZ** [comment]
Oh we were doing `using Requests`. ez mode.

**Comment by malmaud** [comment]
I'm just going to reexport `post` in Requests since too many things are relying on that export, if there are no objections.

**Comment by IainNZ** [comment]
Was the reason for not exporting them that they "pun" on Base things?

**Comment by malmaud** [comment]
Partly it was the fact that many of the HTTP verbs are highly likely to
shadow or be shadowed by user identifiers (delete, head, options,
patch,...), and partly that 'get' puns on Base.get.

**Comment by kshyatt** [comment]
This is working now it looks like.
