### ISSUE TITLE
ERROR: LoadError:  failed to create a precompiled cache file

### ISSUE THREAD

**Issue by diegozea** [IainNZ/Coverage.jl#87]
I found [this problem using Travis and Coveralls](https://travis-ci.org/diegozea/MIToS.jl):

```
ERROR: LoadError: LoadError: __precompile__(true) but require failed to create a precompiled cache file
 in require at ./loading.jl:219
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:271
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:271
 in require at ./loading.jl:210
 in process_options at ./client.jl:284
 in _start at ./client.jl:411
while loading /home/travis/.julia/v0.4/Coverage/src/coveralls.jl, in expression starting on line 5
while loading /home/travis/.julia/v0.4/Coverage/src/Coverage.jl, in expression starting on line 185
```

**Comment by timholy** [comment]
You just have to do what I've been doing, and submit a precompile directive at the top of each dependent file. E.g., https://github.com/JuliaLang/JSON.jl/pull/121

**Comment by IainNZ** [comment]
The problem is actually in GnuTLS, and has nothing to do with Coverage.jl despite the perhaps unclear message.

**Comment by IainNZ** [comment]
Here is an issue you can track the problem with https://github.com/JuliaWeb/GnuTLS.jl/issues/54
@malmaud said he'd take a look

**Comment by diegozea** [comment]
@timholy I already have that line... Is this correct? https://github.com/diegozea/MIToS.jl/blob/master/src/MIToS.jl

**Comment by IainNZ** [comment]
The issues has nothing to do with that, but yes that is correct (if your package can be precompiled)

**Comment by timholy** [comment]
To make it reliable, it has to be in all dependent packages too.

But crucially: if a package can't be precompiled (e.g., it doesn't load, or doesn't pass its tests when precompiled), then you **can't precompile any of the packages that depend on it**. So you should add `__precompile__(false)` in your package, to prevent any attempt from precompilation.

See e.g. https://github.com/JuliaLang/Tk.jl/commit/e861cfc220ee0db80f98749d4e6b43fed1faa93d for an example of a package where I blocked it.
