### ISSUE TITLE
Exception when processing baremodule

### ISSUE THREAD

**Issue by omus** [IainNZ/Coverage.jl#94]
Coverage can't seem to process baremodules. When including a `baremodule` in a package when `process_folder()` processes the file the following exception is raised:

```
ERROR: BoundsError: attempt to access 0-element Array{Any,1}
  at index [1]
 in getindex at ./array.jl:282
 in function_body_lines! at /Users/omus/.julia/v0.4/Coverage/src/parser.jl:25
 in function_body_lines! at /Users/omus/.julia/v0.4/Coverage/src/parser.jl:33
 in anonymous at /Users/omus/.julia/v0.4/Coverage/src/Coverage.jl:153
 in open at ./iostream.jl:114
 in amend_coverage_from_src! at /Users/omus/.julia/v0.4/Coverage/src/Coverage.jl:147
 in process_file at /Users/omus/.julia/v0.4/Coverage/src/Coverage.jl:184
 in process_folder at /Users/omus/.julia/v0.4/Coverage/src/Coverage.jl:206
 in process_folder at /Users/omus/.julia/v0.4/Coverage/src/Coverage.jl:198
```

I've managed to reproduce this exception by creating a new repo and adding a baremodule to the main source file.

**Comment by IainNZ** [comment]
Oh strange, surprised that hasn't come up before. I don't really know how that parser code works, but I'd love a PR to fix it!

**Comment by omus** [comment]
I'll take a look into it tomorrow. I figured it was best that I open the issue first.

**Comment by IainNZ** [comment]
Yes indeed, its good to know.
